#!/bin/bash

echo "📦 Growcado NPM Publishing Guide"
echo "=================================="
echo ""
echo "🚀 QUICK COMMANDS (from root directory):"
echo ""
echo "Patch releases (recommended for bug fixes):"
echo "  pnpm run publish:sdk:patch     # Publish SDK with patch version bump"
echo "  pnpm run publish:react:patch   # Publish React with patch version bump"  
echo "  pnpm run publish:all:patch     # Publish both packages with patch bump"
echo ""
echo "Minor releases (for new features):"
echo "  pnpm run publish:sdk:minor     # Publish SDK with minor version bump"
echo "  pnpm run publish:react:minor   # Publish React with minor version bump"
echo ""
echo "Major releases (for breaking changes):"
echo "  pnpm run publish:sdk:major     # Publish SDK with major version bump"
echo "  pnpm run publish:react:major   # Publish React with major version bump"
echo ""
echo "🧪 DRY RUN COMMANDS (test without publishing):"
echo "  pnpm run publish:dry-run:sdk   # Test SDK publishing process"
echo "  pnpm run publish:dry-run:react # Test React publishing process"
echo ""
echo "🛠️  MANUAL COMMANDS:"
echo "  ./scripts/publish-package.sh sdk patch      # Manual SDK publish"
echo "  ./scripts/publish-package.sh react minor    # Manual React publish"
echo "  ./scripts/publish-package-dry-run.sh sdk patch  # Manual dry-run"
echo ""
echo "📁 INDIVIDUAL PACKAGE COMMANDS:"
echo "  cd packages/sdk && pnpm run publish:patch   # From SDK directory"
echo "  cd packages/react && pnpm run publish:minor # From React directory"
echo ""
echo "🔄 WHAT HAPPENS DURING PUBLISHING:"
echo "  1. 🔨 Build the package (and dependencies)"
echo "  2. 📈 Bump version in source package.json"
echo "  3. 📋 Copy updated package.json to dist/"
echo "  4. 🔄 Transform workspace dependencies to npm versions"
echo "  5. 🚀 Publish from dist/ directory to npm"
echo "  6. 📝 Create git commit with version change"
echo "  7. 🏷️  Create git tag (e.g., @growcado/sdk@1.0.1)"
echo ""
echo "✅ CURRENT PACKAGE VERSIONS:"
SDK_VERSION=$(node -p "require('./packages/sdk/package.json').version")
REACT_VERSION=$(node -p "require('./packages/react/package.json').version")
echo "  @growcado/sdk: $SDK_VERSION"
echo "  @growcado/react: $REACT_VERSION"
echo ""
echo "⚠️  PREREQUISITES:"
echo "  - You must be logged into npm: npm login"
echo "  - You must have publish permissions for @growcado/* packages"
echo "  - Working directory should be clean (commit changes first)"
echo ""
echo "📚 For more info, see: ./scripts/publish-package.sh --help" 